import streamlit as st

legal_terms = {
    "acquittal": "Judgment that a criminal defendant has not been proven guilty beyond a reasonable doubt.",
    "affidavit": "A written statement of facts confirmed by the oath of the party making it. Affidavits must be notarized or administered by an officer of the court with such authority.",
    "affirmed": "Judgment by appellate courts where the decree or order is declared valid and will stand as decided in the lower court.",
    "Alford plea": "A defendant’s plea that allows him to assert his innocence but allows the court to sentence the defendant without conducting a trial. Essentially, the defendant is admitting that the evidence is sufficient to show guilt.",
    "allegation": "Something that someone says happened.",
    "answer": "The formal written statement by a defendant responding to a civil complaint and setting forth the grounds for defense.",
    "appeal": "A request made after a trial, asking another court (usually the court of appeals) to decide whether the trial was conducted properly.",
    "appellate": "About appeals; an appellate court has the power to review the judgment of another lower court or tribunal.",
    "arraignment": "A proceeding in which an individual who is accused of committing a crime is brought into court, told of the charges, and asked to plead guilty or not guilty.",
    "arrest warrant": "A written order directing the arrest of a party. Arrest warrants are issued by a judge after a showing of probable cause.",
    "bail": "Security given for the release of a criminal defendant or witness from legal custody (usually in the form of money) to secure his/her appearance on the day and time appointed.",
    "bankruptcy": "Refers to statutes and judicial proceedings involving persons or businesses that cannot pay their debts and seek the assistance of the court in getting a fresh start.",
    "bench trial": "Trial without a jury in which a judge decides the facts.",
    "beyond a reasonable doubt": "Standard required to convict a criminal defendant of a crime. The prosecution must prove the guilt so that there is no reasonable doubt to the jury that the defendant is guilty.",
    "binding precedent": "A prior decision by a court that must be followed without a compelling reason or significantly different facts or issues.",
    "brief": "A written statement submitted by the lawyer for each side in a case that explains to the judge(s) why they should decide the case in favor of that lawyer's client.",
    "capital offense": "A crime punishable by death.",
    "case law": "The use of court decisions to determine how other law should apply in a given situation.",
    "chambers": "A judge's office.",
    "charge": "The law that the police believe the defendant has broken.",
    "charge to the jury": "The judge's instructions to the jury concerning the law that applies to the facts of the case.",
    "chief judge": "The judge who has primary responsibility for the administration of a court.",
    "circumstantial evidence": "All evidence that is not direct evidence (such as eyewitness testimony).",
    "clerk of court": "An officer appointed by the court to work with the chief judge in overseeing the court's administration.",
    "common law": "The legal system that originated in England and is now in use in the United States.",
    "complaint": "A written statement by the plaintiff stating the wrongs allegedly committed by the defendant.",
    "continuance": "Decision by a judge to postpone trial until a later date.",
    "contract": "An agreement between two or more persons that creates an obligation to do or not to do a particular thing.",
    "conviction": "A judgment of guilt against a criminal defendant.",
    "counsel": "Legal advice; a term used to refer to lawyers in a case.",
    "counterclaim": "A claim that a defendant makes against a plaintiff.",
    "court": "Government entity authorized to resolve legal disputes.",
    "court reporter": "A person who makes a word-for-word record of what is said in court.",
    "cross-examine": "Questioning of a witness by the attorney for the other side.",
    "damages": "Money paid by defendants to successful plaintiffs in civil cases to compensate the plaintiffs for their injuries.",
    "default judgment": "A judgment rendered because of the defendant's failure to answer or appear.",
    "defendant": "In a civil suit, the person complained against; in a criminal case, the person accused of the crime.",
    "defense table": "The table where the defense lawyer sits with the defendant in the courtroom.",
    "deposition": "An oral statement made before an officer authorized by law to administer oaths.",
    "direct evidence": "Evidence that supports a fact without an inference.",
    "discovery": "Lawyers' examination, before trial, of facts and documents in possession of the opponents to help the lawyers prepare for trial.",
    "docket": "A log containing brief entries of court proceedings.",
    "en banc": "Court sessions with the entire membership of a court participating.",
    "evidence": "Information presented in testimony or in documents that is used to persuade the fact finder.",
    "exculpatory evidence": "Evidence which tends to show the defendant’s innocence.",
    "exhibit": "Physical evidence or documents that are presented in a court proceeding.",
    "federal question": "Jurisdiction given to federal courts in cases involving the interpretation and application of the U.S. Constitution.",
    "felony": "A crime carrying a penalty of more than a year in prison.",
    "file": "To place a paper in the official custody of the clerk of court.",
    "grand jury": "A body of citizens who listen to evidence of criminal allegations and determine whether there is probable cause.",
    "habeas corpus": "A writ often used to bring a prisoner before the court to determine the legality of his imprisonment.",
    "hearsay": "Statements by a witness who did not see or hear the incident in question but learned about it through secondhand information.",
    "impeachment": "The process of calling something into question or the constitutional process of accusing high officers of misconduct.",
    "inculpatory evidence": "Evidence which tends to show the defendant’s guilt.",
    "indictment": "The formal charge issued by a grand jury stating that there is enough evidence to justify having a trial.",
    "in forma pauperis": "Permission given to a person to sue without payment of court fees on claim of indigence or poverty.",
    "information": "A formal accusation by a government attorney that the defendant committed a misdemeanor.",
    "initial hearing": "Court proceeding in which the defendant learns of his rights and the charges against him.",
    "injunction": "An order of the court prohibiting (or compelling) the performance of a specific act.",
    "interrogatories": "Written questions asked to one party by an opposing party, who must answer them in writing under oath.",
    "interview": "A meeting with the police or prosecutor.",
    "issue": "The disputed point in a disagreement between parties in a lawsuit.",
    "judge": "Government official with authority to decide lawsuits brought before courts.",
    "judgment": "The official decision of a court finally determining the respective rights and claims of the parties.",
    "jurisdiction": "The legal authority of a court to hear and decide a case.",
    "juror": "A person who is on the jury.",
    "jury": "Persons selected according to law and sworn to inquire into and declare a verdict on matters of fact.",
    "jury instructions": "A judge's explanation to the jury before it begins deliberations of the questions it must answer.",
    "jury pool": "The group of people from which the actual jury is chosen.",
    "jurisprudence": "The study of law and the structure of the legal system.",
    "lawsuit": "A legal action started by a plaintiff against a defendant.",
    "law clerk": "Assist judges with research and drafting of opinions.",
    "librarian": "Meets the informational needs of the judges and lawyers.",
    "litigation": "A case, controversy, or lawsuit.",
    "magistrate judges": "Judicial officers who assist U.S. district court judges in getting cases ready for trial.",
    "misdemeanor": "Usually a petty offense, a less serious crime than a felony, punishable by less than a year of confinement.",
    "mistrial": "An invalid trial caused by fundamental error.",
    "motion": "Attempt to have a limited issue heard by the court.",
    "nolo contendere": "No contest. Has the same effect as a plea of guilty but may not be considered an admission of guilt for any other purpose.",
    "oath": "A promise to tell the truth.",
    "objection": "A protest by an attorney, challenging a statement or question made at trial.",
    "opinion": "A judge's written explanation of a decision of the court.",
    "oral argument": "An opportunity for lawyers to summarize their position before the court in an appeal.",
    "panel": "In appellate cases, a group of judges (usually three) assigned to decide the case.",
    "parties": "Plaintiffs and defendants (petitioners and respondents) to lawsuits.",
    "petit jury": "A group of citizens who hear the evidence presented by both sides at trial.",
    "plaintiff": "The person who files the complaint in a civil lawsuit.",
    "plea": "In a criminal case, the defendant's statement pleading 'guilty' or 'not guilty'.",
    "plea deal": "Agreement between the defendant and prosecutor where the defendant pleads guilty in exchange for a concession by the prosecutor.",
    "pleadings": "Written statements of the parties in a civil case of their positions.",
    "precedent": "A court decision that serves as an example or rule to be followed in future cases.",
    "pretrial conference": "A meeting between the judge and attorneys to discuss the issues and prepare for trial.",
    "probation": "A sentence that allows a defendant to remain in the community under supervision.",
    "probable cause": "A reasonable belief that a person has committed a crime.",
    "prosecution": "The party who represents the government in a criminal case.",
    "public defender": "A lawyer employed by the government to represent defendants who cannot afford private attorneys.",
    "reasonable doubt": "The level of certainty a juror must have to find the defendant guilty.",
    "rebuttal": "Evidence or argument introduced to contradict or disprove facts presented by the opposing party.",
    "remand": "To send a case back to the lower court from which it was appealed.",
    "respondent": "The party against whom a petition is filed in an appeal.",
    "sentence": "The punishment ordered by a court.",
    "settlement": "Agreement between the parties to resolve a dispute before going to trial.",
    "sequester": "To separate the jury from outside influences during a trial.",
    "subpoena": "A court order requiring a person to appear in court to testify or produce evidence.",
    "testimony": "Statements made by witnesses under oath in a trial.",
    "tort": "A civil wrong committed by one person against another, resulting in harm.",
    "trial": "Court procedure for resolving disputes, during which evidence is presented.",
    "trial court": "The court that hears and determines a case before any appeals.",
    "verdict": "The decision of a jury in a case.",
    "warrant": "A court order directing police to arrest someone, search property, or seize evidence.",
    "witness": "A person who testifies in court to provide information about a case."
}

# heading 
st.title("Legal Terms Glossary Bot")


term = st.text_input("Type a legal term: ")

if term:
    # fetch the definition for the entered term (convert to lowercase to match dictionary keys)
    definition = legal_terms.get(term.lower(), "Term not found.")
    
    # display term and definition
    st.write(f"**{term.capitalize()}**: {definition}")

